// Generate a minimal empty .frag model seed for WebIfcViewer Step 5
import { createRequire } from 'module';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const require = createRequire(import.meta.url);

const { IfcImporter } = require('../../node_modules/@thatopen/fragments/dist/index.cjs');

const MINIMAL_IFC = `ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
FILE_NAME('minimal.ifc','2024-01-01T00:00:00',(''),(''),(''),(''),'');
FILE_SCHEMA(('IFC4'));
ENDSEC;
DATA;
#1= IFCORGANIZATION($,'BubbleGraph',$,$,$);
#2= IFCAPPLICATION(#1,'1.0','BubbleGraph','BG');
#3= IFCOWNERHISTORY(#4,#2,$,.NOTDEFINED.,$,$,$,0);
#4= IFCPERSONANDORGANIZATION(#5,#1,$);
#5= IFCPERSON($,'User',$,$,$,$,$,$);
#6= IFCDIRECTION((1.,0.,0.));
#7= IFCDIRECTION((0.,0.,1.));
#8= IFCCARTESIANPOINT((0.,0.,0.));
#9= IFCAXIS2PLACEMENT3D(#8,#7,#6);
#10= IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.0E-5,#9,$);
#11= IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
#12= IFCSIUNIT(*,.AREAUNIT.,$,.SQUARE_METRE.);
#13= IFCSIUNIT(*,.VOLUMEUNIT.,$,.CUBIC_METRE.);
#14= IFCUNITASSIGNMENT((#11,#12,#13));
#15= IFCPROJECT('1i9hLQqMb9fhi2rvp5hbXA',#3,'BubbleGraph',$,$,$,$,(#10),#14);
ENDSEC;
END-ISO-10303-21;`;

async function main() {
  const importer = new IfcImporter();
  importer.wasm = { path: resolve(__dirname, '../../node_modules/web-ifc/') + '/', absolute: true };

  const bytes = Buffer.from(MINIMAL_IFC, 'utf8');
  try {
    const fragBuf = await importer.process({ bytes: new Uint8Array(bytes), raw: true });
    const outPath = resolve(__dirname, '../../src/lib/emptyFragModel.b64.ts');
    const b64 = Buffer.from(fragBuf).toString('base64');
    const ts = `// Auto-generated by gen_empty_frag.mjs — do not edit manually.
// Minimal IFC4 project converted to raw (uncompressed) fragments format.
// Used as seed buffer for editor.createElements() in fragModelBuilder.ts
export const EMPTY_FRAG_MODEL_B64 = '${b64}';\n`;
    writeFileSync(outPath, ts, 'utf8');
    console.log(`Written ${fragBuf.byteLength} bytes -> ${outPath}`);
  } catch (e) {
    console.error('FAILED:', e.message);
    process.exit(1);
  }
}

main();
